name: Build and Deploy Code

on: [push, pull_request]

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v4
      - name: say hi to edo
        run: echo "Hi Edo!"
